### ISSUE TITLE
sitelinks opened with extenison .php return source code instead of 404

### ISSUE THREAD

**Issue by Draluak** [beebmx/kirby-blade#2]
By installing this plugin, all sitelinks can be immediately accessed by appending the extension php and will return html source code instead of a 404 response. This affects plain php templates as well as blade templates and will probably cause serious SEO issues.

![image](https://user-images.githubusercontent.com/51517303/60687700-8982e380-9eb0-11e9-9e26-dc24035063ec.png)

It can be simply reproduced by setting up the starterkit, add the extension an open url-to-starterkit/notes.php

As Kirby uses its own redirect magic through index.php, it seems that this issue can't be solved by simply adding .htaccess rule for php extension.

**Comment by beebmx** [comment]
This is fixed in the last update (2.0.0)
