### ISSUE TITLE
Blade anonymous components don't work within snippets

### ISSUE THREAD

**Issue by PaulMorel** [beebmx/kirby-blade#3]
If you try to call a component within a Kirby snippet, an Exception gets thrown.

Take this setup for example:

```blade
{{-- site/templates/components/alert.blade.php --}}
<div class="alert">
    Hello
</div>
```

```blade
{{-- site/snippets/header.blade.php --}}
<header>
    <x-alert/>
</header>
```

```blade
{{-- site/templates/default.blade.php --}}
<!doctype html>
<html>
    <head>
    </head>
    <body>
        @snippet('header')
    </body>
</html>
```

An exception gets thrown: `Method Illuminate\View\View::__toString() must not throw an exception, caught InvalidArgumentException: Unable to locate a class or view for component [alert].`

---

I thought maybe I could use Blade's `@include` directive instead as a workaround, so I moved the `site/snippets/header.blade.php` file to `site/templates/snippets/header.blade.php` and update `default.blade.php` accordingly.

```blade
{{-- site/templates/default.blade.php --}}
<!doctype html>
<html>
    <head>
    </head>
    <body>
        @include('snippets.header')
    </body>
</html>
```

Doesn't work either. I get a different Exception: `Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Call to a member function get() on array (View: D:\Dev\www\example\staging\site\templates\snippets\header.blade.php) (View: D:\Dev\www\example.com\staging\site\templates\snippets\header.blade.php) (View: D:\Dev\www\example.com\staging\site\templates\snippets\header.blade.php)`

**Comment by beebmx** [comment]
Right now the components only works outside snippets (only in the templates directory).
But if you need to implement the same behavior.

You can do something like:

```blade
{{-- site/templates/components/alert.blade.php --}}
<div class="alert">
    Hello
</div>
```

```blade
{{-- site/templates/partials/header.blade.php --}}
<header>
    <x-alert/>
</header>
```

```blade
{{-- site/templates/default.blade.php --}}
<!doctype html>
<html>
    <head>
    </head>
    <body>
        @include('partials.header')
    </body>
</html>
```

And you will get the same result.

**Comment by PaulMorel** [comment]
@beebmx I appreciate the fast reply. I already tried that work around and I get another Exception. I updated my post at the same time you replied.

**Comment by beebmx** [comment]
I used exactly you blade files and I can't reproduce your error.
And the result is the expected.
Is there anything else in the code?

<img width="650" alt="image" src="https://user-images.githubusercontent.com/2191576/82971323-040c9400-9f98-11ea-9293-9c6b80a6af03.png">

**Comment by PaulMorel** [comment]
Yes there's other code, I just didn't include it because I didn't think it was relevant. Turns out it was. I found the problem. 

I had another `@snippet` inside my template that seems to conflict with includes and components. If I change `@snippet` for `@include` it works. I don't think it's 100% related with the original issue though. I'll investigate further in the future.

Thanks for the help

**Comment by beebmx** [comment]
There's no problem.
I think the new version with components and snippets are great.
The code at the end looks cleaner.

And if you want to do it even cleaner, you can use a component for your header.

`<x-header />`
