### ISSUE TITLE
x-dynamic-component error

### ISSUE THREAD

**Issue by HYR** [beebmx/kirby-blade#6]
I get an error when trying to use `<x-dynamic-component :component="$myComponent" class="mt-4" />`:

![image](https://user-images.githubusercontent.com/5200901/109013389-576b5a00-7670-11eb-9bfd-0f0a5d412722.png)
]

The error above says "Unable to locate a class or view for component [{$component}]." even though I know the component exists because I can call it directly using the standard `<x-[componentName]... />` syntax. I'm not sure. Any idea?

**Note:** I'm new to using Laravel Blade. Perhaps I'm not understanding something or perhaps there's an issue with using dynamic components.

**Comment by beebmx** [comment]
You are right.
In the latest versión `3.x` Kirby-blade has support for `illuminate/view 8.x` but the dynamic-component is not yet implemented.
I have planed to do it shortly, but it's in my schedule right now.

But you can use normal component as usual (in the `site/templates/components` directory).

In the mean while you can use include for that purpose, like `@include('partials.' . $dynamicComponent, ['data' => $data])`.

We know there is another issue with the brand new directive `@once` than requires `ramsey/uuid` package, and we planed to included soon. In case you need to implement the `@once` directive, just included in your composer.json file.

**Comment by HYR** [comment]
Thanks, that's super helpful to have a work around for both the dynamic-component and `@once` until they are solved. And thanks for providing this plugin, I'm already really enjoying using Laravel Blade within my Kirby site!

**Comment by HYR** [comment]
Hey @beebmx! Checking to see if this will be prioritized soon. 🙂

**Comment by beebmx** [comment]
@HYR sorry for the delay.
But the dynamic-component it's now available.
